name: 'Agent Example RHEL Build'

on:
  workflow_dispatch:

jobs:

  build:

    name: 'Container Agent Build'
    runs-on: ubuntu-latest
    environment: main
    env:
      CONTEXT: "devops-agents/linux/rhel8/agent"
      DOCKERFILE_NAME: "Agent.Dockerfile"

      IMAGE_NAME: "azure-devops-agent-agent-rhel8"
      TAGS: "latest"

      GITHUB_REGISTRY: "ghcr.io"

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          logout: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.8.0
        with:
          build-args: |
            ACCEPT_EULA="y"
            NORMAL_USER="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)"
            AZP_AGENT_NAME="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)"
            AZP_URL=${{ secrets.AZP_URL }}
            AZP_TOKEN=${{ secrets.AZP_TOKEN }}
            AZP_POOL=${{ secrets.AZP_POOL }}
            AZP_WORK=${{ secrets.AZP_WORK }}

          context: ${{ env.CONTEXT }}
          file: "${{ env.CONTEXT }}/${{ env.DOCKERFILE_NAME }}"
          tags: "${{ env.GITHUB_REGISTRY }}/${{ secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAGS }}"
          labels: |
            DateCreated=$(date +'%Y-%m-%d')

          push: true
          github-token: ${{ secrets.GH_TOKEN }}