name: 'Base RHEL Build'

on:
  push:
    branches:
      - main
      - dev
      - mvp
      - feature*
  workflow_dispatch:

jobs:

  build:

    name: 'Container Base Build'
    runs-on: ubuntu-latest
    environment: main
    env:
      CONTEXT: "devops-agents/linux/rhel8/base"
      DOCKERFILE_NAME: "Base.Dockerfile"

      PYTHON3_VERSION: 3.9.10

      REGISTRY: "ghcr.io"
      IMAGE_NAME: "azure-devops-agent-base-rhel8"
      TAGS: "latest"

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Login, Build and push Container images
        working-directory: ${{ env.CONTEXT }}
        run: |
          
          podman login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{ env.REGISTRY }} && \
        
          podman build \
            --file="${{ env.DOCKERFILE_NAME }}" \
            --tag="${{ env.REGISTRY }}/${{secrets.USERNAME }}/${{ env.IMAGE_NAME}}:${{ env.TAGS }}" \
            --build-arg ACCEPT_EULA="y" \
            --build-arg PYTHON3_VERSION=${{ env.PYTHON3_VERSION }} \
            --label=DateCreated=$(date +'%Y-%m-%d') \
            --squash && \

          podman push "${{ env.REGISTRY }}/${{secrets.USERNAME }}/${{ env.IMAGE_NAME}}:${{ env.TAGS }}" && \
        
          podman logout --all && \
        
          rm -rf ${XDG_RUNTIME_DIR}/containers/auth.json