name: 'Base Windows 20H2 Build'

on:
  push:
    branches:
      - main
      - dev
      - mvp
      - feature*
  workflow_dispatch:

jobs:

  build:

    name: 'Container Base Build'
    runs-on: windows-latest
    environment: main
    env:
      CONTEXT: "devops-agents/windows/20H2/base"
      DOCKERFILE_NAME: "Base.Dockerfile"

      PYTHON3_VERSION: "@latest"
      NORMAl_USER: ContainerAdministrator

      REGISTRY: "ghcr.io"
      IMAGE_NAME: "azure-devops-agent-base-win20H2:"
      TAGS: "latest"

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - name: Login, Build and push Container images
        working-directory: ${{ env.CONTEXT }}
        run: |
          
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{ env.REGISTRY }} ; `
        
          docker build --file=${{ env.DOCKERFILE_NAME }} --tag=$ {{ env.REGISTRY }}/${{ secrets.USER }}/${{ env.IMAGE_NAME }}$ {{ env.TAGS }} --build-arg ACCEPT_EULA=y --build-arg NORMAL_USER=${{ env.NORMAL_USER }} --build-arg PYTHON3_VERSION=${{ env.PYTHON3_VERSION }} . ; `

          docker push "${{ env.REGISTRY }}/${{secrets.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAGS }}" ; `
        
          docker logout ${{ env.REGISTRY }}