---
name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

variables:
  - group: "DOCKER_SECRETS"

jobs:
  - template: ./templates/windows/build-base.yml
    parameters:
      USERNAME: $(USERNAME)
      PASSWORD: $(PASSWORD)
      CONTEXT: "devops-agents/windows/server/base"
      DOCKERFILE_NAME: "Base.Dockerfile"
      REGISTRY: "ghcr.io"
      PYTHON3_VERSION: "@latest"
      IMAGE_NAME: "azure-devops-agent-base-winseverltsc2022"
      TAGS: ":latest"