---
name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

variables:
  - group: "DOCKER_SECRETS"
  - group: "LINUX_AZURE_DEVOPS_SECRETS"

jobs:
  - template: ./templates/linux/build-agent.yml
    parameters:
      AGENT_AMOUNT: "3"
      USERNAME: $(USERNAME)
      PASSWORD: $(PASSWORD)
      NORMAL_USER: $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)
      CONTEXT: "../devops-agents/linux/rhel8/agent"
      DOCKERFILE_NAME: "Agent.Dockerfile"
      REGISTRY: "ghcr.io"
      IMAGE_NAME: "azure-devops-agent-rhel8-agent-"
      TAGS: ":latest"
      AZP_URL: $(AZP_URL)
      AZP_TOKEN: $(AZP_TOKEN)
      AZP_POOL: $(AZP_POOL)
      AZP_AGENT_NAME: $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)
      AZP_WORK: "_work"