---
name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

parameters:

  - name: CONTEXT
    displayName: "The the path to your dockerfile"
    default: "devops-agents/windows/server/base"
    type: string

  - name: DOCKERFILE_NAME
    displayName: "The name of the Dockerfile"
    default: "Base.Dockerfile"
    type: string
    values:
      - "Dockerfile"
      - "Containerfile"
      - "Base.Dockerfile"
      - "Agent.Dockerfile"

  - name: PYTHON3_VERSION
    displayName: "The version of python to be installed by from get.scoop.sh"
    default: "@latest"
    type: string

  - name: REGISTRY
    displayName: "The target registry"
    default: "ghcr.io"
    type: string
    values:
      - "ghcr.io"
      - "docker.io"
      - "quay.io"
      - "registry.redhat.com"
      - "azurecr.io"

  - name: IMAGE_NAME
    displayName: "The name of the image"
    default: "azure-devops-agent-base-winseverltsc2022"
    type: string

  - name: TAGS
    displayName: "The tag of the image"
    type: string
    default: ":latest"

  - name: HOSTED_AGENT_IMAGE
    displayName: "The name of the vmImage"
    default: "windows-2022"
    type: string

  - name: SECRETS_VARIABLE_GROUP
    displayName: "The name of the variable group holding the secrets"
    default: "DOCKER_SECRETS"
    type: string

  - name: USERNAME
    displayName: "Username to be passed for registry login, should reference a secret"
    default: $(USERNAME)
    type: string

  - name: PASSWORD
    displayName: "Password or access token for registry login, remember to store this in a keyvault or encrypted variable"
    default: $(PASSWORD)
    type: string

  - name: TEMPLATE_PATH
    displayName: "The name of the variable group holding the secrets"
    default: "./templates/windows/build-base.yml"
    type: string

variables:
  - group: ${{ parameters.SECRETS_VARIABLE_GROUP }}

jobs:
  - template: ${{ parameters.TEMPLATE_PATH }}
    parameters:
      USERNAME: ${{ parameters.USERNAME }}
      PASSWORD: ${{ parameters.PASSWORD }}
      CONTEXT: ${{ parameters.CONTEXT }}
      DOCKERFILE_NAME: ${{ parameters.DOCKERFILE_NAME }}
      REGISTRY: ${{ parameters.REGISTRY  }}
      PYTHON3_VERSION: ${{ parameters.PYTHON3_VERSION }}
      IMAGE_NAME: ${{ parameters.IMAGE_NAME }}
      TAGS: ${{ parameters.TAGS }}